### ISSUE TITLE
Heroku App does not work anymore

### ISSUE THREAD

**Issue by leonadler** [pablodenadai/angular2-seed-project#80]
The URL linked in the title, http://angular2-seed.io/ (redirecting to http://angular2-seed.herokuapp.com/) results in an Application Error.

**Comment by pablodenadai** [comment]
Thanks for the heads up.

I've just checked the Heroku logs and found out what the issue is.

```
[09:00:04] Starting 'build'...
[09:00:05] 'build' errored after 289 ms
[09:00:05] Error: File not found with singular glob: /app/typings/main.d.ts
   at Glob.<anonymous> (/app/node_modules/glob-stream/index.js:39:11)
   at Glob.g (events.js:273:16)
   at Glob.emit (events.js:182:7)
   at emitOne (events.js:90:13)
   at Glob._processSimple2 (/app/node_modules/glob/glob.js:652:12)
   at Glob._stat2 (/app/node_modules/glob/glob.js:736:12)
   at /app/node_modules/glob/glob.js:640:10
   at done (/app/node_modules/glob/glob.js:159:12)
   at Glob._finish (/app/node_modules/glob/glob.js:172:8)
[09:00:05] 'build' errored after 426 ms
[09:00:05] Did you forget to signal async completion?
   at RES (/app/node_modules/inflight/inflight.js:23:14)
   at FSReqWrap.oncomplete (fs.js:82:15)
   at lstatcb_ (/app/node_modules/glob/glob.js:728:12)
   at f (/app/node_modules/once/once.js:17:25)
Process exited with status 1
```

I think it's because since the new version of Typings it deploys the definition files `.d.ts` to a different folder and Gulp can't find them.

Unfortunately I haven't had time to work on this project lately. But please feel free to send a PR.
